name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Validate tag matches Cargo.toml version
        shell: bash
        run: |
          TAG="${{ github.event.release.tag_name }}"
          if [ -z "$TAG" ]; then TAG="${GITHUB_REF#refs/tags/}"; fi
          VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml | head -n1)
          echo "Tag: $TAG"
          echo "Cargo.toml version: $VERSION"
          if [ "v$VERSION" != "$TAG" ] && [ "$VERSION" != "$TAG" ]; then
            echo "Tag does not match Cargo.toml version" >&2
            exit 1
          fi

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          if [ -z "$CARGO_REGISTRY_TOKEN" ]; then
            echo "Missing crates.io token in secrets.CARGO_REGISTRY_TOKEN" >&2
            exit 1
          fi
          cargo publish --locked --token "$CARGO_REGISTRY_TOKEN"

